### ISSUE TITLE
Membership delivers unexpected results

### ISSUE THREAD

**Issue by f14m07** [liedekef/events-made-easy#231]
**Describe the bug**
The membership form has not changed. Visitors register on the site. They will then normally be directed to the payment page. The EME person is created, but not the member. However, the WP account has been created.

**To Reproduce**
Go to https://vogue-et-reve.fr and choose "Adhérer". Fill the form to see the error message

**Expected behavior**
the payment page must open

**Screenshots**
See the joined file with the error message

**Online Demo**
You can test with your inscription

**Log output**
![erreur vogue-et-reve](https://github.com/liedekef/events-made-easy/assets/113473805/7392916a-6a39-4b29-8a7e-82289c0478b5)

I don't see anything in the logs 

**Additional context**
I can't say when the bug start. I have the last EME and WP version and 8.2 PHP. I have the same error on the production and local site

**Comment by liedekef** [comment]
According to other tickets, you have changed extra eme files by getting them from source (which is always dangerous), so you will need to check your php logs.

**Comment by f14m07** [comment]
On this site I have change no files from dev version.

**Comment by f14m07** [comment]
the php log show nothing so I don't understand

**Comment by liedekef** [comment]
internal server error always points to a php code issue. Any test of me on your site doesn't reveal more info ...
I'll try to reproduce it here later on

**Comment by liedekef** [comment]
Based on this ticket, you use changed files: https://github.com/liedekef/events-made-easy/discussions/225 (and I warned about that in the discussion too).
Obviously I don't release until testing is completed, so in this case not all files were probably ok on github (at that time).
Update all php files to the ones from github and try again, local testing reveals no membership issues here.

**Comment by liedekef** [comment]
Btw: it's no use to give me an account on your WP installation, php code errors are only logged in files. If not, you need to check where/how they are logged or give a 100% sure method of reproducing your problem with stock EME.

**Comment by f14m07** [comment]
The EME files on this site are from the latest version v 2.3.72. I do not use the modified #225 files.
I confirm the bug on my production site and my local website. I'm still looking at the logs but I can't see any errors at the moment.

**Comment by f14m07** [comment]
Excuse-me my php error file was not well edited. These the lines of the php error.log
````
  thrown in /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-people.php on line 3383
[12-Jul-2023 13:05:53 UTC] PHP Warning:  Undefined variable $person_id in /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-functions.php on line 3448
[12-Jul-2023 13:05:53 UTC] PHP Stack trace:
[12-Jul-2023 13:05:53 UTC] PHP   1. {main}() /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-admin/admin-ajax.php:0
[12-Jul-2023 13:05:53 UTC] PHP   2. do_action($hook_name = 'wp_ajax_nopriv_eme_add_member') /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-admin/admin-ajax.php:203
[12-Jul-2023 13:05:53 UTC] PHP   3. WP_Hook->do_action($args = [0 => '']) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/plugin.php:517
[12-Jul-2023 13:05:53 UTC] PHP   4. WP_Hook->apply_filters($value = '', $args = [0 => '']) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/class-wp-hook.php:332
[12-Jul-2023 13:05:53 UTC] PHP   5. eme_add_member_ajax('') /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/class-wp-hook.php:308
[12-Jul-2023 13:05:53 UTC] PHP   6. eme_add_update_member($member_id = *uninitialized*, $send_mail = *uninitialized*) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php:4468
[12-Jul-2023 13:05:53 UTC] PHP   7. eme_db_insert_member($line = ['membership_id' => '2', 'person_id' => 102, 'related_member_id' => 0, 'status' => 0, 'paid' => 0, 'pg' => '', 'pg_pid' => '', 'extra_charge' => 0, 'status_automatic' => 1, 'start_date' => '0000-00-00', 'end_date' => '0000-00-00', 'payment_date' => '0000-00-00 00:00', 'discount' => 0, 'discountids' => '', 'dcodes_entered' => [], 'dcodes_used' => [], 'dgroupid' => 0, 'properties' => ['usage_count' => 0], 'member_id' => 0], $membership = ['membership_id' => '2', 'name' => 'Equipiers', 'description' => 'Suivi des adhÃ©rents et des cotisations', 'type' => 'rolling', 'start_date' => '2020-06-01', 'duration_count' => '3', 'duration_period' => 'months', 'properties' => ['one_free_period' => '1', 'grace_period' => '5', 'reminder_days' => '5', 'remove_pending_days' => 0, 'allow_renewal' => 'on', 'renewal_cutoff_days' => '0', 'create_wp_user' => 'on', 'price' => '15', 'extra_charge' => '0', 'currency' => 'EUR', 'vat_pct' => '0', 'contact_id' => '-1', 'member_form_tpl' => '20', 'member_form_text' => '', 'familymember_form_tpl' => '', 'familymember_form_text' => '', 'member_added_tpl' => '44', 'member_added_text' => '', 'payment_form_header_tpl' => '24', 'payment_form_header_text' => '', 'payment_form_footer_tpl' => '0', 'payment_form_footer_text' => 'Ceci est le pied de page du formulaire de paiement, il nâest pas utilisÃ©', 'payment_success_tpl' => '0', 'payment_success_text' => '', 'addpersontogroup' => [...], 'member_template_id' => '', 'use_stripe' => '1', 'use_offline' => '1', 'offline_payment_tpl' => '0', 'offline_payment_text' => '', 'new_subject_format' => 'Bienvenue sur LOCAL Vogue #_FIRSTNAME', 'new_body_format_tpl' => '21', 'new_body_text' => '', 'newmember_attach_ids' => '', 'contact_new_subject_format' => 'Un nouveau membre s\'est inscrit sur LOCAL', 'contact_new_body_format_tpl' => '30', 'contact_new_body_text' => '', 'updated_subject_format' => 'AdhÃ©sion Ã  l\'association LOCAL a Ã©tÃ© mise Ã  jour', 'updated_body_format_tpl' => '26', 'updated_body_text' => '', 'extended_subject_format' => 'AdhÃ©sion LOCAL prolongÃ©e', 'extended_body_format_tpl' => '25', 'extended_body_text' => '', 'paid_subject_format' => 'Le paiement de votre adhÃ©sion LOCAL a Ã©tÃ© reÃ§u', 'paid_body_format_tpl' => '28', 'paid_body_text' => '', 'contact_paid_subject_format' => 'Paiement du membre reÃ§u - LOCAL', 'contact_paid_body_format_tpl' => '28', 'contact_paid_body_text' => '', 'reminder_subject_format' => 'Rappel dâexpiration pour #_MEMBERSHIPNAME LOCAL', 'reminder_body_format_tpl' => '27', 'reminder_body_text' => '', 'stop_subject_format' => 'Au revoir #_FIRSTNAME votre adhÃ©sion LOCAL est Ã©chue', 'stop_body_format_tpl' => '29', 'stop_body_text' => '', 'contact_stop_subject_format' => 'L\'adhÃ©sion LOCAL d\'un membre a expirÃ©e', 'contact_stop_body_format_tpl' => '31', 'contact_stop_body_text' => '', 'contact_ipn_subject_format' => 'La passerelle de paiement a reÃ§u une cotisation LOCAL', 'contact_ipn_body_format_tpl' => '33', 'contact_ipn_body_text' => '', 'use_captcha' => 0, 'use_recaptcha' => 0, 'use_hcaptcha' => 0, 'use_cfcaptcha' => 0, 'max_usage_count' => 0, 'registration_wp_users_only' => 0, 'family_membership' => 0, 'family_maxmembers' => 10, 'dyndata' => [...], 'dyndata_all_fields' => 0, 'captcha_only_logged_out' => 0, 'attendancerecord' => 0, 'discount' => '', 'discountgroup' => '', 'skippaymentoptions' => 0, 'use_paypal' => 0, 'use_legacypaypal' => 0, 'use_2co' => 0, 'use_webmoney' => 0, 'use_fdgg' => 0, 'use_mollie' => 0, 'use_payconiq' => 0, 'use_worldpay' => 0, 'use_opayo' => 0, 'use_sumup' => 0, 'use_braintree' => 0, 'use_instamojo' => 0, 'use_mercadopago' => 0, 'use_fondy' => 0]], $member_id = *uninitialized*) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php:1031
[12-Jul-2023 13:05:53 UTC] PHP   8. eme_create_wp_user($person = ['person_id' => '102', 'lastname' => 'Webmaster', 'firstname' => 'Fred', 'email' => 'frederic1956@yahoo.fr', 'status' => '1', 'phone' => '0625253904', 'wp_id' => '0', 'address1' => '4 rue des champs', 'address2' => '', 'city' => 'La Rochelle', 'zip' => '17000', 'state' => '', 'country' => '', 'state_code' => '', 'country_code' => '', 'lang' => 'en', 'massmail' => '1', 'gdpr' => '0', 'properties' => ['wp_delete_user' => 0, 'image_id' => 0], 'creation_date' => '2023-07-12 15:05:52', 'modif_date' => '2023-07-12 15:05:52', 'gdpr_date' => NULL, 'birthdate' => '2020-04-01', 'birthplace' => '', 'related_person_id' => '0', 'random_id' => 'b58802456e2f302da5976bfd61bce92eed413a7a32d6a3', 'bd_email' => '1', 'newsletter' => '1']) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php:230
[12-Jul-2023 13:05:53 UTC] PHP Warning:  Trying to access array offset on value of type null in /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-functions.php on line 3448
[12-Jul-2023 13:05:53 UTC] PHP Stack trace:
[12-Jul-2023 13:05:53 UTC] PHP   1. {main}() /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-admin/admin-ajax.php:0
[12-Jul-2023 13:05:53 UTC] PHP   2. do_action($hook_name = 'wp_ajax_nopriv_eme_add_member') /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-admin/admin-ajax.php:203
[12-Jul-2023 13:05:53 UTC] PHP   3. WP_Hook->do_action($args = [0 => '']) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/plugin.php:517
[12-Jul-2023 13:05:53 UTC] PHP   4. WP_Hook->apply_filters($value = '', $args = [0 => '']) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/class-wp-hook.php:332
[12-Jul-2023 13:05:53 UTC] PHP   5. eme_add_member_ajax('') /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/class-wp-hook.php:308
[12-Jul-2023 13:05:53 UTC] PHP   6. eme_add_update_member($member_id = *uninitialized*, $send_mail = *uninitialized*) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php:4468
[12-Jul-2023 13:05:53 UTC] PHP   7. eme_db_insert_member($line = ['membership_id' => '2', 'person_id' => 102, 'related_member_id' => 0, 'status' => 0, 'paid' => 0, 'pg' => '', 'pg_pid' => '', 'extra_charge' => 0, 'status_automatic' => 1, 'start_date' => '0000-00-00', 'end_date' => '0000-00-00', 'payment_date' => '0000-00-00 00:00', 'discount' => 0, 'discountids' => '', 'dcodes_entered' => [], 'dcodes_used' => [], 'dgroupid' => 0, 'properties' => ['usage_count' => 0], 'member_id' => 0], $membership = ['membership_id' => '2', 'name' => 'Equipiers', 'description' => 'Suivi des adhÃ©rents et des cotisations', 'type' => 'rolling', 'start_date' => '2020-06-01', 'duration_count' => '3', 'duration_period' => 'months', 'properties' => ['one_free_period' => '1', 'grace_period' => '5', 'reminder_days' => '5', 'remove_pending_days' => 0, 'allow_renewal' => 'on', 'renewal_cutoff_days' => '0', 'create_wp_user' => 'on', 'price' => '15', 'extra_charge' => '0', 'currency' => 'EUR', 'vat_pct' => '0', 'contact_id' => '-1', 'member_form_tpl' => '20', 'member_form_text' => '', 'familymember_form_tpl' => '', 'familymember_form_text' => '', 'member_added_tpl' => '44', 'member_added_text' => '', 'payment_form_header_tpl' => '24', 'payment_form_header_text' => '', 'payment_form_footer_tpl' => '0', 'payment_form_footer_text' => 'Ceci est le pied de page du formulaire de paiement, il nâest pas utilisÃ©', 'payment_success_tpl' => '0', 'payment_success_text' => '', 'addpersontogroup' => [...], 'member_template_id' => '', 'use_stripe' => '1', 'use_offline' => '1', 'offline_payment_tpl' => '0', 'offline_payment_text' => '', 'new_subject_format' => 'Bienvenue sur LOCAL Vogue #_FIRSTNAME', 'new_body_format_tpl' => '21', 'new_body_text' => '', 'newmember_attach_ids' => '', 'contact_new_subject_format' => 'Un nouveau membre s\'est inscrit sur LOCAL', 'contact_new_body_format_tpl' => '30', 'contact_new_body_text' => '', 'updated_subject_format' => 'AdhÃ©sion Ã  l\'association LOCAL a Ã©tÃ© mise Ã  jour', 'updated_body_format_tpl' => '26', 'updated_body_text' => '', 'extended_subject_format' => 'AdhÃ©sion LOCAL prolongÃ©e', 'extended_body_format_tpl' => '25', 'extended_body_text' => '', 'paid_subject_format' => 'Le paiement de votre adhÃ©sion LOCAL a Ã©tÃ© reÃ§u', 'paid_body_format_tpl' => '28', 'paid_body_text' => '', 'contact_paid_subject_format' => 'Paiement du membre reÃ§u - LOCAL', 'contact_paid_body_format_tpl' => '28', 'contact_paid_body_text' => '', 'reminder_subject_format' => 'Rappel dâexpiration pour #_MEMBERSHIPNAME LOCAL', 'reminder_body_format_tpl' => '27', 'reminder_body_text' => '', 'stop_subject_format' => 'Au revoir #_FIRSTNAME votre adhÃ©sion LOCAL est Ã©chue', 'stop_body_format_tpl' => '29', 'stop_body_text' => '', 'contact_stop_subject_format' => 'L\'adhÃ©sion LOCAL d\'un membre a expirÃ©e', 'contact_stop_body_format_tpl' => '31', 'contact_stop_body_text' => '', 'contact_ipn_subject_format' => 'La passerelle de paiement a reÃ§u une cotisation LOCAL', 'contact_ipn_body_format_tpl' => '33', 'contact_ipn_body_text' => '', 'use_captcha' => 0, 'use_recaptcha' => 0, 'use_hcaptcha' => 0, 'use_cfcaptcha' => 0, 'max_usage_count' => 0, 'registration_wp_users_only' => 0, 'family_membership' => 0, 'family_maxmembers' => 10, 'dyndata' => [...], 'dyndata_all_fields' => 0, 'captcha_only_logged_out' => 0, 'attendancerecord' => 0, 'discount' => '', 'discountgroup' => '', 'skippaymentoptions' => 0, 'use_paypal' => 0, 'use_legacypaypal' => 0, 'use_2co' => 0, 'use_webmoney' => 0, 'use_fdgg' => 0, 'use_mollie' => 0, 'use_payconiq' => 0, 'use_worldpay' => 0, 'use_opayo' => 0, 'use_sumup' => 0, 'use_braintree' => 0, 'use_instamojo' => 0, 'use_mercadopago' => 0, 'use_fondy' => 0]], $member_id = *uninitialized*) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php:1031
[12-Jul-2023 13:05:53 UTC] PHP   8. eme_create_wp_user($person = ['person_id' => '102', 'lastname' => 'Webmaster', 'firstname' => 'Fred', 'email' => 'frederic1956@yahoo.fr', 'status' => '1', 'phone' => '0625253904', 'wp_id' => '0', 'address1' => '4 rue des champs', 'address2' => '', 'city' => 'La Rochelle', 'zip' => '17000', 'state' => '', 'country' => '', 'state_code' => '', 'country_code' => '', 'lang' => 'en', 'massmail' => '1', 'gdpr' => '0', 'properties' => ['wp_delete_user' => 0, 'image_id' => 0], 'creation_date' => '2023-07-12 15:05:52', 'modif_date' => '2023-07-12 15:05:52', 'gdpr_date' => NULL, 'birthdate' => '2020-04-01', 'birthplace' => '', 'related_person_id' => '0', 'random_id' => 'b58802456e2f302da5976bfd61bce92eed413a7a32d6a3', 'bd_email' => '1', 'newsletter' => '1']) /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php:230
[12-Jul-2023 13:05:53 UTC] PHP Fatal error:  Uncaught TypeError: array_intersect_key(): Argument #2 must be of type array, null given in /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-people.php:3383
Stack trace:
#0 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-people.php(3383): array_intersect_key(Array, NULL)
#1 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-functions.php(3448): eme_db_update_person(NULL, Array)
#2 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php(230): eme_create_wp_user(Array)
#3 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php(1031): eme_db_insert_member(Array, Array)
#4 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-members.php(4468): eme_add_update_member()
#5 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/class-wp-hook.php(308): eme_add_member_ajax('')
#6 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#7 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-admin/admin-ajax.php(203): do_action('wp_ajax_nopriv_...')
#9 {main}
  thrown in /Users/fredericmoriniere/Local Sites/voguer/app/public/wp-content/plugins/events-made-easy/eme-people.php on line 3383

**Comment by liedekef** [comment]
Ha, now that's indeed a bug (typo) :-)
This is the fix: https://github.com/liedekef/events-made-easy/commit/7573d00afc5c0ef8953658df75781ab6b8aabbe6

**Comment by f14m07** [comment]
that is fine. Thanks for this quick solution
