### ISSUE TITLE
EME Critical Error in line 6585

### ISSUE THREAD

**Issue by refugeindhamma** [liedekef/events-made-easy#320]
**Describe the bug**
I was changing the setting for "Allow RSVP from ... before the event starts" to 32 days and "Allow RSVP until ... before the event starts" to 1 day. Then, after updating, I got this error:
```
"There has been a critical error on this website. Please check your site admin email inbox for instructions."
```

After accessing the event at "Events" tab again, the change has been recorded.

**Log output**
Received an email with the following error details:
```
Error Details
=============
An error of type E_ERROR was caused in line 6585 of the file /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-content/plugins/events-made-easy/eme-rsvp.php. Error message: Uncaught TypeError: Cannot access offset of type string on string in /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-content/plugins/events-made-easy/eme-rsvp.php:6585
Stack trace:
#0 /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-content/plugins/events-made-easy/eme-events.php(9220): eme_manage_waitinglist()
#1 /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-content/plugins/events-made-easy/eme-events.php(677): eme_db_update_event()
#2 /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-includes/class-wp-hook.php(310): eme_events_page()
#3 /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#4 /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/refugeindhamma/htdocs/www.refugeindhamma.com/wp-admin/admin.php(259): do_action()
#6 {main}
  thrown
```

**Version info**
PHP version: 8.0.30
EME version: 2.4.10
Wordpress version: 6.3.1

**Comment by liedekef** [comment]
This is a typo. I'll fix it and release a new version asap.

**Comment by liedekef** [comment]
2.4.11 released for this
