### ISSUE TITLE
Data protection settings give fatal error

### ISSUE THREAD

**Issue by StickyPixels** [liedekef/events-made-easy#5]
Hi,
When I click on Data Protection Settings I get a fatal error. The text shown is:
```
Fatal error: Uncaught ArgumentCountError: 2 arguments are required, 1 given in D:\[server path]\wp-content\plugins\events-made-easy\eme-options.php:2072 Stack trace: #0 D:\[server path]\wp-content\plugins\events-made-easy\eme-options.php(2072): sprintf() #1 D:\[server path]\wp-includes\class-wp-hook.php(308): eme_options_page() #2 D:\[server path]\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters() #3 D:\[server path]\wp-includes\plugin.php(517): WP_Hook->do_action() #4 D:\[server path]\wp-admin\admin.php(259): do_action() #5 {main} thrown in D:\[server path]\wp-content\plugins\events-made-easy\eme-options.php on line 2072

There has been a critical error on this website. Please check your site admin email inbox for instructions.
```

Using  latest version 2.3.34 on Windows server, PHP 8.0.26
Checked for plugin or theme conflicts.

**Comment by liedekef** [comment]
Correct, typo present there. Released a new version 2.3.35 (containing some other small fixes too)
